spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quizapp
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: salsob7y@gmail.com
    password: fbij uoqh jccp eaww
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 7777
